apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Zenardi/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      valueFiles:
        - values-production.yaml
      valuesObject:
        replicaCount: 2
        service:
          type: NodePort
      parameters:
        - name: replicaCount
          value: '2'
  destination:
    server: https://kubernetes.default.svc
    namespace: default