apiVersion: v1
kind: Service
metadata:
  name: rollout-gateway-stable
  namespace: gateway-lab
spec:
  selector:
    app: rollout-gateway
  ports:
  - port: 3000
    name: http

---

apiVersion: v1
kind: Service
metadata:
  name: rollout-gateway-canary
  namespace: gateway-lab
spec:
  selector:
    app: rollout-gateway
  ports:
  - port: 3000
    name: http
